[project]
name = "repio-intelligence"
version = "0.0.1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
  "python-dotenv>=1.0.1",
  "langchain>=0.3.0",
  "langchain-community>=0.3.0",
  "langchainhub>=0.1.21",
  "langchain-anthropic>=0.2.1",
  "langchain-groq>=0.2.0",
  "langchain-core>=0.3.2",
  "langgraph>=0.2.22",
  "langchain-openai>=0.2.0",
  "pydantic>=2.9.2",
  "temporalio>=1.7.1",
  "toml>=0.10.2",
  "packaging>=24.1",
  "ipykernel>=6.29.5",
  "langgraph-checkpoint-postgres>=1.0.7",
  "langgraph-sdk>=0.1.30",
  "langchain-postgres>=0.0.12",
  "psycopg2-binary>=2.9.9",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv]
dev-dependencies = ["ipykernel>=6.29.5"]

[tool.hatch.build.targets.wheel]
packages = ["src/matcher", "src/parser", "src/utils"]
