[project]
name = "repio-ai"
version = "0.0.1"
description = "AI Agents for repio.co"
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["langchain>=0.3.11",
  "langchain-community>=0.3.11",
  "langchain-anthropic>=0.3.0",
  "langchain-core>=0.3.25",
  "langgraph>=0.2.59",
  "langchain-openai>=0.2.12",
  "pydantic>=2.10.3",
  "langchain-aws>=0.2.9",
  "trustcall>=0.0.26",
  "python-dotenv>=1.0.1"]

[build-system]
requires = ["setuptools>=73.0.0",
  "wheel"]
build-backend = "setuptools.build_meta"

[tool.uv]
dev-dependencies = ["ipykernel>=6.29.5",
  "langgraph-cli[inmem]>=0.1.56",
  "langgraph-sdk>=0.1.33",
  "mypy>=1.13.0",
  "ruff>=0.6.6",
  "toml>=0.10.2"]

[tool.setuptools]
packages = ["matcher",
  "scorecard",
  "utils"]

[tool.ruff]
include = ["*.py",
  "*.pyi",
  "*.ipynb"]

[tool.setuptools.package-dir]
matcher = "src/matcher"
scorecard = "src/scorecard"
utils = "src/utils"

[tool.setuptools.package-data]
"*" = ["py.typed"]

[tool.ruff.lint]
select = ["E",
  "F",
  "I",
  "D",
  "D401",
  "T201",
  "UP"]
ignore = ["UP006",
  "UP007",
  "UP035",
  "D417",
  "E501",
  "D100"]

[tool.ruff.lint.per-file-ignores]
"tests/*" = ["D",
  "UP"]
"ntbk/*" = ["D",
  "UP",
  "T201"]

[tool.ruff.lint.pydocstyle]
convention = "google"

