import uuid
from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field

from feeder.models.job_offer import JobOfferDescription
from setup.models.job_posting import JobPosting
from setup.models.question import Question
from setup.models.scorecard import Scorecard
from setup.models.synthesis import Synthesis


class StreamCustomEvents(str, Enum):
    """Task for stream events."""

    CLEAN_RESOURCE = "clean_resources"
    GENERATE_JOB_POSTING = "generate_job_posting"
    GENERATE_QUESTIONS = "generate_questions"
    GENERATE_SYNTHESIS = "generate_synthesis"
    GENERATE_SCORECARD_STRUCTURE = "generate_scorecard_structure"
    GENERATE_CONTEXT = "generate_context"


class StreamCustomEventsStatus(str, Enum):
    """Status for stream events."""

    IN_PROGRESS = "in_progress"
    COMPLETED = "completed"


class ResourceOrigin(str, Enum):
    """Enum for different resource origins."""

    HUMAN = "human"  # Directly provided by a human through UI
    AGENT = "agent"  # Auto-scraped by AI agent


class ResourceType(str, Enum):
    """Enum for different resource types."""

    TEXT = "text"
    WEB = "web"
    PDF = "pdf"


class BaseResource(BaseModel):
    """Base class for all resource types."""

    id: uuid.UUID = Field(..., description="The ID of the resource")

    source: ResourceOrigin = Field(
        ..., description="Source of the context (human/agent)"
    )
    content_type: ResourceType = Field(..., description="Type of the context")
    content: str = Field(..., description="The actual content")


class ScorecardInputGraphState(BaseModel):
    """State of the scorecard input graph."""

    resources: List[BaseResource] = Field(
        ...,
        description="List of all resources related to the job posting",
    )


class ScorecardGraphState(ScorecardInputGraphState):
    """State of the scorecard graph."""

    job_posting: Optional[JobPosting] = Field(
        None, description="Job posting with all the context provided by the user"
    )
    scorecard: Optional[Scorecard] = Field(
        None, description="Scorecard with all the criteria and questions"
    )
    questions: Optional[List[Question]] = Field(
        None,
        description="List of questions generated by the LLM and answered by the human",
    )
    synthesis: Optional[Synthesis] = Field(
        None, description="Synthesis of the scorecard"
    )
    feeder_input: Optional[JobOfferDescription] = Field(
        None, description="Input for the feeder subgraph"
    )

    def get_formatted_questions(self) -> List[str]:
        """Get the questions."""
        return [
            (f"Question: {question.question}\nAnswer: {question.final_answer}")
            for question in self.questions
        ]
