from typing import List, Optional

from pydantic import BaseModel, Field

from scorecard_generator.models.question import Question
from scorecard_generator.models.scorecard import Scorecard
from scorecard_generator.models.synthesis import Synthesis


class ScorecardGraphState(BaseModel):
    """State of the scorecard graph."""

    raw_job_posting: str = Field(
        ..., description="Raw job posting with all the context provided by the user"
    )
    scorecard: Optional[Scorecard] = Field(
        None, description="Scorecard with all the criteria and questions"
    )
    web_context: Optional[List[str]] = Field(
        None, description="List of context elements from the web search"
    )
    generated_questions: Optional[List[Question]] = Field(
        None,
        description="List of questions generated by the LLM and answered by the human",
    )
    human_feedback: Optional[List[str]] = Field(
        None, description="List of human feedback to apply to the scorecard"
    )
    human_context: Optional[List[str]] = Field(
        None, description="List of context elements from the human feedback"
    )
    synthesis: Optional[Synthesis] = Field(
        None, description="Synthesis of the scorecard"
    )


class ScorecardInputGraphState(BaseModel):
    """State of the scorecard input graph."""

    raw_job_posting: str = Field(
        ..., description="Raw job posting with all the context provided by the user"
    )
