from typing import List, Optional

from pydantic import BaseModel, Field

from scorecard.models.job_posting import JobPosting
from scorecard.models.question import ListQuestions
from scorecard.models.scorecard import Scorecard
from scorecard.models.synthesis import Synthesis


class ScorecardInputGraphState(BaseModel):
    """State of the scorecard input graph."""

    context_initial: str = Field(
        ..., description="Raw job posting with all the context provided by the user"
    )


class ScorecardGraphState(ScorecardInputGraphState):
    """State of the scorecard graph."""

    job_posting: Optional[JobPosting] = Field(
        None, description="Job posting with all the context provided by the user"
    )
    scorecard: Optional[Scorecard] = Field(
        None, description="Scorecard with all the criteria and questions"
    )
    generated_questions: Optional[ListQuestions] = Field(
        None,
        description="List of questions generated by the LLM and answered by the human",
    )
    human_feedback: Optional[List[str]] = Field(
        None, description="List of human feedback to apply to the scorecard"
    )
    context_enriched: Optional[List[str]] = Field(
        None, description="List of context elements from the web search"
    )
    context_additional: Optional[List[str]] = Field(
        None, description="List of context elements from the human feedback"
    )
    synthesis: Optional[Synthesis] = Field(
        None, description="Synthesis of the scorecard"
    )
