from typing import List, Optional
from pydantic import BaseModel, Field

from scorecard.models.question import Question
from scorecard.models.scorecard import Scorecard
from scorecard.sub_graph.enrichment.state import GlobalContext


class ScorecardGraphState(BaseModel):
    raw_job_posting: str = Field(
        ..., description="Raw job posting with all the context provided by the user"
    )
    scorecard: Optional[Scorecard] = Field(
        None, description="Scorecard with all the criteria and questions"
    )
    web_context: Optional[List[str]] = Field(
        None, description="List of context elements from the web search"
    )
    generated_questions: Optional[List[Question]] = Field(
        None,
        description="List of questions generated by the LLM and answered by the human",
    )
    human_feedback: Optional[List[str]] = Field(
        None, description="List of human feedback to apply to the scorecard"
    )
    human_context: Optional[List[str]] = Field(
        None, description="List of context elements from the human feedback"
    )


class ScorecardInputGraphState(BaseModel):
    raw_job_posting: str = Field(
        ..., description="Raw job posting with all the context provided by the user"
    )
